### ISSUE TITLE
PASO 4 - OBRA- monto

### ISSUE THREAD

**Issue by leonardoleenen** [leonardoleenen/registroconstructores#10]
Agregar una seccion que este siempre visible entre la navegacion de las diferentes pestañas en donde  el sistema debera ir calculando estos campos.
Monto vigente: esto sería monto inicial de contrato + redeterminaciones + ampliaciones
Certificado a la fecha: esto sería la sumatoria de las certificaciones/facturación mensual
Saldo

**Comment by leonardoleenen** [comment]
Este tema lo tendrían que ver con @imgermi

**Comment by imgermi** [comment]
La idea es que sean campos no editables, sino simplemente de estado (visualización de datos), que se van actualizando en real time?

Tendría sentido poner estos componentes en el top navbar, donde está (hoy) el avatar del usuario para Cerrar Sesión y el botón de Guardar?
