### ISSUE TITLE
Visual Clue. - ART. 13

### ISSUE THREAD

**Issue by leonardoleenen** [leonardoleenen/registroconstructores#193]
Agregar, al costado del estado de los trámites, un distintivo (cuadradito), cuando una empresa que actualiza (solo para empresas que actualizan) acaba de cargar una obra "Pre Adjudicada" o "Adjudicada".
El cuadradito deberá decir, simplemente:
Art. 13
Es para diferenciar internamente entre trámites que hay que darles un tratamiento rápido.
Una vez aprobada esa obra, si en posteriores actualizaciones sigue en ese estado, ya está, lo que importaba era aprobarla rápido a la primera, para que aparezca en el certificado.

**Comment by leonardoleenen** [comment]
Esta regla aplica unicamente a las empresas que están INSCRIPTAS (o con proceso de actualización de datos) y donde agregan nuevas obras en estado ADJUDICADA y PRE ADJUDICADA

**Comment by leonardoleenen** [comment]
@imgermi @marianoel1983 esta mejora aplica a las cards de Bandeja de BackOffice como la card del Constructor. tienen que agregar un Visual Clue que permita ver RAPIDAMENTE si ese tramite aplica o no a ART.13

**Comment by imgermi** [comment]
![badge](https://user-images.githubusercontent.com/20772265/115023439-2d2a6180-9e95-11eb-8189-c72d83f2fa59.png)
![tag](https://user-images.githubusercontent.com/20772265/115023446-2f8cbb80-9e95-11eb-8369-40c0d13893fe.png)
![badge-tooltip(active)](https://user-images.githubusercontent.com/20772265/115023449-30255200-9e95-11eb-88bf-b241a07bef0d.png)
![badge-tooltip](https://user-images.githubusercontent.com/20772265/115023453-31567f00-9e95-11eb-86ac-a678b48d8ccf.png)
